name: CI Pipeline - Build & Push to ECRs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Mandatory for AWS OIDC authentication to mint the JSON Web Token (JWT)
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ROLE_TO_ASSUME: arn:aws:iam::042357172638:role/github-actions-ecr-role
  ECR_REPOSITORY: 042357172638.dkr.ecr.us-east-1.amazonaws.com/atul2909/gha-demo

jobs:
  ci:
    name: Build, Test & Push Image
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Printers
        run: echo "${{vars.PRINTO}}"
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-ECR-CI

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with: ${{secrets.ATUL_LOGIN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Printer
        run: |
          echo "running in ${{github.repository}}"
          echo "running in ${{github.sha}}"
          echo "running in ${{runner.os}}"
          
          

